services:
  - type: web
    name: jobportal-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn findjob.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: findjob.settings
      - key: PYTHON_VERSION
        value: 3.11