# Generated by Django 5.2.3 on 2025-07-01 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjobapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=30)),
                ('mode', models.CharField(max_length=10)),
                ('salary', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=200)),
                ('empid', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, to='findjobapp.credentials')),
            ],
        ),
    ]
