# Generated by Django 5.2.3 on 2025-07-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjobapp', '0005_jobseekerregistraion_delete_jobseekerdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerregistraion',
            name='job',
        ),
        migrations.AddField(
            model_name='jobseekerregistraion',
            name='empid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='findjobapp.credentials'),
        ),
    ]
