# Generated by Django 5.2.3 on 2025-07-02 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjobapp', '0006_remove_jobseekerregistraion_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='findjobapp.jobdata')),
                ('seekerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='findjobapp.credentials')),
            ],
        ),
    ]
