# Generated by Django 5.2.3 on 2025-07-03 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjobapp', '0008_applicants_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeeregisteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.CharField(max_length=100)),
                ('empid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='findjobapp.credentials')),
            ],
        ),
    ]
