# Generated by Django 5.2.3 on 2025-07-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findjobapp', '0009_employeeregisteration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerregistraion',
            name='username',
        ),
    ]
