# Generated by Django 5.2.3 on 2025-07-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjobapp', '0010_remove_jobseekerregistraion_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdata',
            name='posteddate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
