# Generated by Django 5.2.3 on 2025-07-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjobapp', '0011_alter_jobdata_posteddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdata',
            name='isfilled',
            field=models.BooleanField(default=False),
        ),
    ]
