# Generated by Django 5.2.3 on 2025-07-04 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjobapp', '0012_jobdata_isfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='empid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='findjobapp.credentials'),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='seekerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='findjobapp.credentials'),
        ),
    ]
